use std::os::raw::{c_ushort, c_uint, c_uchar, c_int, c_void};
#[repr(C)]
pub struct _zend_module_entry {
    size: c_ushort,
    zend_api: c_uint,
    zend_debug: c_uchar,
    zts: c_uchar,
    ini_entry: *mut c_void,
    deps: *mut c_void,
    name: *mut c_void,
    functions: *mut c_void,
    module_startup_func: *mut c_void,
    module_shutdown_func: *mut c_void,
    request_startup_func: *mut c_void,
    request_shutdown_func: *mut c_void,
    info_func: *mut c_void,
    version: *mut c_void,
    globals_size: c_int,
    globals_ptr: *mut c_void,
    globals_ctor: *mut c_void,
    globals_dtor: *mut c_void,
    post_deactivate_func: *mut c_void,
    module_started: c_int,
    type_: c_uchar,
    handle: *mut c_void,
    module_number: c_int,
    build_id: *mut c_void,
}
